### ISSUE TITLE
Artifact on maven

### ISSUE THREAD

**Issue by ak80** [slavap/gwt-joda-java-time#1]
I would like to have a look at gwt-joda-java-time but I am unable to find the artifact in maven central

Is this still correct?
```
<dependency>
  <groupId>com.vx.jtime</groupId>
  <artifactId>gwt-joda-java-time</artifactId>
  <version>0.0.1</version>
  <classifier>sources</classifier>
  <scope>provided</scope>
</dependency>
```

**Comment by slavap** [comment]
@ak80 Just download, build, and deploy to your local artifactory. I've never published it on maven central.

**Comment by ak80** [comment]
@slavap ok I see, I was just so used to finding almost everything published. I will use it from my local repository which is fine for now.

Thank you, and I hope to dive in soon!
